"""remove price category

Revision ID: 03c365753b14
Revises: 62c2639354c1
Create Date: 2026-01-18 17:30:03.356597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03c365753b14'
down_revision: Union[str, Sequence[str], None] = '62c2639354c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'price_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('price_category', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
