"""create_brands_table

Revision ID: 2346510e03e4
Revises: 0b80cb49a979
Create Date: 2026-01-16 17:37:25.279702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2346510e03e4'
down_revision: Union[str, Sequence[str], None] = '0b80cb49a979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_of_origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('price_category', sa.Integer(), nullable=True),
    sa.Column('total_locations', sa.Integer(), nullable=True),
    sa.Column('regions_present', sa.JSON(), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('elo_trend', sa.Float(), nullable=False),
    sa.Column('rank_trend', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_elo'), 'brands', ['elo'], unique=False)
    op.drop_table('testitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testitem',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('testitem_pkey'))
    )
    op.drop_index(op.f('ix_brands_elo'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
