"""refactor brands remove countries_active and price

Revision ID: 2d17c2021613
Revises: 03c365753b14
Create Date: 2026-01-18 17:34:49.775162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d17c2021613'
down_revision: Union[str, Sequence[str], None] = '03c365753b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'rank')
    op.drop_column('brands', 'countries_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('countries_active', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
