"""re-apply column change

Revision ID: 5bd19e95683b
Revises: 2082b13e02f4
Create Date: 2026-01-18 19:50:16.708989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bd19e95683b'
down_revision: Union[str, Sequence[str], None] = '2082b13e02f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'description')
    # ### end Alembic commands ###
