"""add store locations

Revision ID: 62c2639354c1
Revises: 8cc21852e201
Create Date: 2026-01-18 16:32:26.196443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62c2639354c1'
down_revision: Union[str, Sequence[str], None] = '8cc21852e201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=False),
    sa.Column('loser_id', sa.Uuid(), nullable=False),
    sa.Column('winner_elo_before', sa.Integer(), nullable=False),
    sa.Column('winner_elo_after', sa.Integer(), nullable=False),
    sa.Column('loser_elo_before', sa.Integer(), nullable=False),
    sa.Column('loser_elo_after', sa.Integer(), nullable=False),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_locations_google_place_id'), 'store_locations', ['google_place_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_locations_google_place_id'), table_name='store_locations')
    op.drop_table('store_locations')
    op.drop_table('matches')
    # ### end Alembic commands ###
