"""add countries_active and match model

Revision ID: 8cc21852e201
Revises: 2346510e03e4
Create Date: 2026-01-16 19:24:02.694399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cc21852e201'
down_revision: Union[str, Sequence[str], None] = '2346510e03e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('countries_active', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'countries_active')
    # ### end Alembic commands ###
